### PR TITLE
[Feature Addition] CLI route introspection

### PR DESCRIPTION
**Pull request by tfdahlin**
Added CLI entrypoint and functionality to inspect the routes and methods implemented by a given class.

### CODE REVIEW

**Comment by tfdahlin** [comment]
With more complex application structure, it can be challenging to quickly identify all routes defined in a web application. This pull request adds a CLI component to pycnic that inspects a specified class (e.g. `pycnic routes main:app`, which inspects the `app` class in `main.py`), in order to determine what routes and methods it implements. 

The implementation is a little bit complex, so if you're curious about the specific details, I would recommend reading the documentation in the code that explains how it works.

I've tested this locally with python 3.6.5, and it seems to work well, but I can't easily test with other versions of python at the moment on my machine. 

If you're comfortable adding this to the library, I'd be happy to write additional documentation for how to use it and add that to this PR as well before merging it to master, and spend time trying to test this on other version of python.

**Comment by tfdahlin** [comment]
@nullism if you wouldn't mind letting me know if this is an addition you're willing to make, that would be greatly appreciated. I want to wait on writing user documentation for the feature until I know if the feature will be accepted or not

**Comment by nullism** [comment]
I'm looking over it now. I'm not opposed to the idea and I think it's a cool addition so far!

**Comment by tfdahlin** [comment]
At some point I'll probably look into a better system of identifying route variables, instead of just displaying the regular expression, but I didn't want to dive into complex parsing like that just yet because I don't know how complex that will actually get. I'm writing the user documentation now, but I might not have it completed until tomorrow

**Comment by tfdahlin** [comment]
Alright, I wrote the documentation, and I believe I updated the links.yaml correctly. I might be able to test on additional python versions tomorrow.

**Comment by nullism** [comment]
Lemme know when you're ready for review and I'll check it over once more and merge it in.  I'm not too concerned about style as it's an isolated script, so the PEP-8 complaints can be ignored. 

Glad you like Pycnic enough to contribute!

**Comment by tfdahlin** [comment]
Sounds great! I'll actually probably fix the PEP-8 complaints before I mark it as ready for review, I just wanted to wait until I confirmed that the changes are backwards compatible to other version of python first before fixing style issues.

I honestly can't get enough of this library, so I'm happy to be able to contribute. Thank you for making it in the first place!

**Comment by tfdahlin** [comment]
I had to make a few changes for this to work as intended in python2, but it seems to be functioning right now. I've tested it using python 2.7.16, 3.6.5, and 3.7.3. It does have a slightly different implementation in python 3.3.x and 3.4.x that I was unable to test. It also does not support python versions 3.0.X through 3.2.X, and raises an exception if the script is called by one of those python versions.

I also did a little shuffling to account for flake8 complaints. 

@nullism I think it's ready to merge if you want to give it a once over

**Review by nullism — APPROVED** [review]
Makes sense to me, I'll work on getting a new build out

**Pull request merged**
